### ISSUE TITLE
pyroma fails in the pre-commit.ci

### ISSUE THREAD

**Issue by mkryvy-cb** [regebro/pyroma#102]
Hey there,
I've been trying to configure this hook for pre-commit ci and getting this error:

```Check package with Pyroma................................................Failed
- hook id: pyroma
- exit code: 2

------------------------------
Checking .
Getting metadata for wheel...
Creating venv isolated environment...
Exception raised during metadata preparation
Traceback (most recent call last):
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/pyroma/projectdata.py", line 75, in get_data
    return get_build_data(path)
           ^^^^^^^^^^^^^^^^^^^^
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/pyroma/projectdata.py", line 62, in get_build_data
    metadata = build_metadata(path, isolated=isolated)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/pyroma/projectdata.py", line 38, in build_metadata
    return build.util.project_wheel_metadata(path, isolated=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/build/util.py", line 51, in project_wheel_metadata
    with build.env.IsolatedEnvBuilder() as env:
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/build/env.py", line 107, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/build/env.py", line 274, in _create_isolated_env_venv
    raise build.FailedProcessError(exc, 'Failed to create venv. Maybe try installing virtualenv.') from None
build.FailedProcessError: Failed to create venv. Maybe try installing virtualenv.
  Command '/tmp/build-env-u19bbeml/bin/python3.11 -m ensurepip --upgrade --default-pip' failed with return code 1
  stdout:
    /tmp/build-env-u19bbeml/bin/python3.11: No module named ensurepip

Neither setup.py nor setup.cfg was found
Traceback (most recent call last):
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/pyroma/projectdata.py", line 75, in get_data
    return get_build_data(path)
           ^^^^^^^^^^^^^^^^^^^^
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/pyroma/projectdata.py", line 62, in get_build_data
    metadata = build_metadata(path, isolated=isolated)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/pyroma/projectdata.py", line 38, in build_metadata
    return build.util.project_wheel_metadata(path, isolated=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/build/util.py", line 51, in project_wheel_metadata
    with build.env.IsolatedEnvBuilder() as env:
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/build/env.py", line 107, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pc/clone/kpOtHGroTwyElj3qiMJyNQ/py_env-python3/lib/python3.11/site-packages/build/env.py", line 274, in _create_isolated_env_venv
    raise build.FailedProcessError(exc, 'Failed to create venv. Maybe try installing virtualenv.') from None
build.FailedProcessError: Failed to create venv. Maybe try installing virtualenv.
  Command '/tmp/build-env-u19bbeml/bin/python3.11 -m ensurepip --upgrade --default-pip' failed with return code 1
  stdout:
    /tmp/build-env-u19bbeml/bin/python3.11: No module named ensurepip
```

and the config is
```
  - repo: https://github.com/regebro/pyroma
    rev: "4.2"
    hooks:
    -   id: pyroma
```

**Comment by regebro** [comment]
There is no dependency on ensurepip in pyroma, I think this is a problem with your setup.
